# Generated by Django 4.2.7 on 2023-11-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answer',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
