# Generated by Django 4.2.3 on 2023-11-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_question_answer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question_answer",
            name="Answer",
            field=models.CharField(default="답변", max_length=2000),
        ),
    ]
